package com.unipi.lykourgoss.edusoftware.statistics.ExamStatistic;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;

/**
 * Created by LykourgosS <lpsarantidis@gmail.com>
 * on 01,July,2019.
 */

@Dao
public interface ExamStatisticDao {

    // methods' code will be auto-generated by Room library

    @Insert
    void insert(ExamStatistic statistic);

    @Update
    void update(ExamStatistic statistic);

    @Delete
    void delete(ExamStatistic statistic);

    @Query("DELETE FROM exam_statistic_table")
    void deleteAll();

    @Query("SELECT * FROM exam_statistic_table ORDER BY dateTime ASC")
    LiveData<List<ExamStatistic>> getAll();

    @Query("SELECT COUNT(id) FROM exam_statistic_table WHERE chapterId = :chapterId GROUP BY id")
    int getTotalTries(String chapterId);

    @Query("SELECT COUNT(id) FROM exam_statistic_table WHERE chapterId = :chapterId AND passTest = :pass GROUP BY id")
    int getTotalFailOrPass(String chapterId, boolean pass);

    @Query("SELECT SUM(millisDuration) / 60000 FROM exam_statistic_table WHERE chapterId = :chapterId")
    long getTotalTimeInMin(String chapterId);
}
