package com.unipi.lykourgoss.edusoftware.CodingFlowExample;

import android.content.Context;
import android.os.AsyncTask;

import androidx.annotation.NonNull;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;
import androidx.sqlite.db.SupportSQLiteDatabase;

/**
 * Created by LykourgosS <lpsarantidis@gmail.com>
 * on 17,June,2019.
 */

//todo to add more entities add them with a comma above
@Database(entities = {Lesson.class}, version = 1)
public abstract class LessonDatabase extends RoomDatabase {

    private static LessonDatabase instance;

    // code of lessonDao() method will be automatically generated by Room,
    // because of the use of Room.databaseBuilder
    public abstract LessonDao lessonDao();

    public static synchronized LessonDatabase getInstance(Context context){
        if (instance == null){
            instance = Room.databaseBuilder(context.getApplicationContext(),
                    LessonDatabase.class, "eduSoftware_database")
                    .fallbackToDestructiveMigration()
                    .addCallback(roomCallback)
                    .build();
        }
        return instance;
    }

    public static RoomDatabase.Callback roomCallback = new RoomDatabase.Callback(){
        @Override
        public void onCreate(@NonNull SupportSQLiteDatabase db) {
            super.onCreate(db);
            new PopulateDbAsyncTask(instance).execute();
        }
    };

    private static class PopulateDbAsyncTask extends AsyncTask<Void, Void, Void>{
        private LessonDao lessonDao;

        public PopulateDbAsyncTask(LessonDatabase lessonDatabase) {
            this.lessonDao = lessonDatabase.lessonDao();
        }

        @Override
        protected Void doInBackground(Void... voids) {
            lessonDao.insert(new Lesson("OCA Java", "", 0, "lpsarantidis@gmail.com"));
            return null;
        }
    }
}
