package com.unipi.lykourgoss.edusoftware.statistics;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;
import androidx.sqlite.db.SupportSQLiteDatabase;

import com.unipi.lykourgoss.edusoftware.statistics.ExamStatistic.ExamStatistic;
import com.unipi.lykourgoss.edusoftware.statistics.ExamStatistic.ExamStatisticDao;
import com.unipi.lykourgoss.edusoftware.statistics.SubsectionStatistic.SubsectionStatistic;
import com.unipi.lykourgoss.edusoftware.statistics.SubsectionStatistic.SubsectionStatisticDao;

/**
 * Created by LykourgosS <lpsarantidis@gmail.com>
 * on 1,July,2019.
 */

// to add more entities add them with a comma above
@Database(entities = {SubsectionStatistic.class, ExamStatistic.class}, version = 1, exportSchema = false)
public abstract class StatisticDatabase extends RoomDatabase {

    private static StatisticDatabase instance;

    // code of Dao() method will be automatically generated by Room,
    // because of the use of Room.databaseBuilder
    public abstract SubsectionStatisticDao SubsectionStatisticDao();
    public abstract ExamStatisticDao ExamStatisticDao();

    public static synchronized StatisticDatabase getInstance(Context context){
        if (instance == null){
            instance = Room.databaseBuilder(context.getApplicationContext(),
                    StatisticDatabase.class, "statistic_database")
                    .fallbackToDestructiveMigration()
                    .addCallback(roomCallback)
                    .build();
        }
        return instance;
    }

    private static Callback roomCallback = new Callback(){
        @Override
        public void onCreate(@NonNull SupportSQLiteDatabase db) {
            super.onCreate(db);
        }
    };
}
