package com.unipi.lykourgoss.edusoftware.filestoremove.codingflowexample.statistics.SubsectionStatistic;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;

/**
 * Created by LykourgosS <lpsarantidis@gmail.com>
 * on 01,July,2019.
 */

@Dao
public interface SubsectionStatisticDao {

    // methods' code will be auto-generated by Room library

    @Insert
    void insert(SubsectionStatistic statistic);

    @Update
    void update(SubsectionStatistic statistic);

    @Delete
    void delete(SubsectionStatistic statistic);

    @Query("DELETE FROM subsection_statistic_table")
    void deleteAll();

    @Query("SELECT * FROM subsection_statistic_table ORDER BY dateTime ASC")
    LiveData<List<SubsectionStatistic>> getAll();
}
